server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: racing-service
  datasource:
    url: jdbc:postgresql://localhost:5432/shoes_db
    username: postgres
    password: 5382
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  web:
    cors:
      allowed:
        origins: '*'
        methods: '*'
        headers: '*'